# Production environment configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:intern_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# API Configuration
api:
  gemini:
    key: {GEMINI_API_KEY}
    url: ${GEMINI_API_URL}
jwt:
  secret: ${JWT_SECRET}
