server:
  port: 8081

app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type

jwt:
  secret: QQsxktuSe5QDRC7SsHnJsp/37uUubNK2244bkFvNcSw=

